# Generated by Django 5.0.1 on 2024-01-14 19:10

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardencalendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='no description available')),
                ('frequency', models.DurationField(default=datetime.timedelta(days=1))),
            ],
        ),
        migrations.CreateModel(
            name='GrowthStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growth_stages', models.CharField(default='Name of growth stage', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('min_time_of_start_within_the_cycle', models.DurationField(blank=True, default=None)),
                ('max_time_of_start_within_the_cycle', models.DurationField(blank=True, default=None)),
                ('min_length_in_days', models.DurationField(blank=True, default=None)),
                ('max_length_in_days', models.DurationField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gardens', to=settings.AUTH_USER_MODEL)),
                ('general_tasks', models.ManyToManyField(blank=True, related_name='gardens', to='gardencalendar.generaltask')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default='no description available')),
                ('min_growth_time', models.DurationField(default=datetime.timedelta(days=1))),
                ('max_growth_time', models.DurationField(default=datetime.timedelta(days=2))),
                ('growth_stages', models.ManyToManyField(blank=True, related_name='plants', to='gardencalendar.growthstage')),
            ],
        ),
        migrations.AddField(
            model_name='growthstage',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_growth_stages', to='gardencalendar.plant'),
        ),
        migrations.CreateModel(
            name='Plant_specific_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='no description available')),
                ('frequency', models.DurationField(default=datetime.timedelta(days=1))),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_tasks', to='gardencalendar.plant')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='plants', to='gardencalendar.plant_specific_task'),
        ),
        migrations.CreateModel(
            name='PlantInGarden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('min_completion', models.DateTimeField(blank=True, default=None)),
                ('max_completion', models.DateTimeField(blank=True, default=None)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardencalendar.garden')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardencalendar.plant')),
            ],
        ),
        migrations.AddField(
            model_name='garden',
            name='plants',
            field=models.ManyToManyField(blank=True, related_name='gardens', through='gardencalendar.PlantInGarden', to='gardencalendar.plant'),
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('frequency', models.DurationField(default=datetime.timedelta(days=1))),
                ('start_date', models.DateField(default=datetime.datetime(2024, 1, 14, 19, 10, 17, 439944, tzinfo=datetime.timezone.utc))),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='gardencalendar.garden')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='garden',
            name='user_tasks',
            field=models.ManyToManyField(blank=True, related_name='gardens', to='gardencalendar.usertask'),
        ),
    ]
