# Generated by Django 5.0.1 on 2024-01-14 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardencalendar', '0002_generaltask_growthstage_garden_plant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantingarden',
            name='growth_phase_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='growthstage',
            name='max_length_in_days',
            field=models.DurationField(blank=True, default='0 00:00:00'),
        ),
        migrations.AlterField(
            model_name='growthstage',
            name='max_time_of_start_within_the_cycle',
            field=models.DurationField(default='0 00:00:00'),
        ),
        migrations.AlterField(
            model_name='growthstage',
            name='min_length_in_days',
            field=models.DurationField(blank=True, default='0 00:00:00'),
        ),
        migrations.AlterField(
            model_name='growthstage',
            name='min_time_of_start_within_the_cycle',
            field=models.DurationField(default='0 00:00:00'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 14, 20, 8, 11, 348913, tzinfo=datetime.timezone.utc)),
        ),
    ]
