# Generated by Django 5.0.1 on 2024-01-07 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardencalendar', '0002_generaltask_growthstage_plant_growthstage_plant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='plant',
        ),
        migrations.AlterField(
            model_name='usertask',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 7, 15, 48, 55, 385109, tzinfo=datetime.timezone.utc)),
        ),
    ]
