# Generated by Django 5.0.1 on 2024-01-07 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardencalendar', '0003_remove_usertask_plant_alter_usertask_start_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Plant_specific_task',
        ),
        migrations.AlterField(
            model_name='usertask',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 7, 18, 43, 33, 513237, tzinfo=datetime.timezone.utc)),
        ),
    ]
