# Generated by Django 5.0.1 on 2024-01-14 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardencalendar', '0003_plantingarden_growth_phase_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 14, 20, 20, 37, 2795, tzinfo=datetime.timezone.utc)),
        ),
    ]
