# Generated by Django 5.0.1 on 2024-01-07 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardencalendar', '0004_rename_task_plant_specific_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='growthstage',
            name='growing_time',
        ),
        migrations.AddField(
            model_name='growthstage',
            name='growth_stages',
            field=models.CharField(default='Name of growth stage', max_length=50),
        ),
        migrations.AddField(
            model_name='growthstage',
            name='max_time_in_days',
            field=models.DurationField(default=datetime.timedelta(days=2)),
        ),
        migrations.AddField(
            model_name='growthstage',
            name='min_time_in_days',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
        migrations.AlterField(
            model_name='growthstage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 7, 19, 27, 12, 136837, tzinfo=datetime.timezone.utc)),
        ),
    ]
