# Generated by Django 5.0.1 on 2024-01-14 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardencalendar', '0004_alter_usertask_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='growthstage',
            name='stage_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='plantingarden',
            name='growth_phase_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 14, 22, 31, 5, 654278, tzinfo=datetime.timezone.utc)),
        ),
    ]
