# Generated by Django 5.0.1 on 2024-01-14 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardencalendar', '0005_growthstage_stage_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='city_state',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='garden',
            name='fall_frost',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='garden',
            name='season_length',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='garden',
            name='spring_frost',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 14, 22, 53, 47, 531345, tzinfo=datetime.timezone.utc)),
        ),
    ]
