# Generated by Django 5.0.1 on 2024-01-14 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardencalendar', '0006_garden_city_state_garden_fall_frost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantingarden',
            name='quantity',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='garden',
            name='city_state',
            field=models.CharField(blank=True, default='leave blank', max_length=25),
        ),
        migrations.AlterField(
            model_name='garden',
            name='fall_frost',
            field=models.CharField(blank=True, default='leave blank', max_length=25),
        ),
        migrations.AlterField(
            model_name='garden',
            name='season_length',
            field=models.CharField(blank=True, default='leave blank', max_length=25),
        ),
        migrations.AlterField(
            model_name='garden',
            name='spring_frost',
            field=models.CharField(blank=True, default='leave blank', max_length=25),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 14, 23, 0, 0, 595292, tzinfo=datetime.timezone.utc)),
        ),
    ]
