# Generated by Django 5.0.1 on 2024-01-15 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardencalendar', '0007_plantingarden_quantity_alter_garden_city_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='x_coord',
            field=models.CharField(blank=True, default='leave blank', max_length=20),
        ),
        migrations.AddField(
            model_name='garden',
            name='y_coord',
            field=models.CharField(blank=True, default='leave blank', max_length=20),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 15, 0, 21, 30, 304114, tzinfo=datetime.timezone.utc)),
        ),
    ]
