# Generated by Django 5.0.1 on 2024-01-15 01:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardencalendar', '0008_garden_x_coord_garden_y_coord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='x_coord',
            field=models.CharField(blank=True, default='leave blank', max_length=40),
        ),
        migrations.AlterField(
            model_name='garden',
            name='y_coord',
            field=models.CharField(blank=True, default='leave blank', max_length=40),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 15, 1, 45, 24, 428647, tzinfo=datetime.timezone.utc)),
        ),
    ]
